zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.30.0.M14
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

kafka:
  image: eventuateio/eventuateio-local-kafka:0.30.0.M14
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181


mysql:
  image: eventuateio/eventuate-tram-mysql:0.20.0.M10
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

mongodb:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"

cdcservice:
  image: eventuateio/eventuate-tram-cdc-mysql-service:0.20.0.M10
  ports:
    - "8099:8080"
  links:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1
    EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_NAME: 1
    EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
