zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.18.0.RELEASE
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

kafka:
  image: test-eventuateio-local-kafka
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181


mysql:
  image: eventuateio/eventuate-tram-mysql:0.7.0.RELEASE
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

mongodb:
  image: mongo:3.0.4
  hostname: mongodb
  command: mongod --smallfiles
  ports:
    - "27017:27017"

cdcservice:
  image: test-eventuate-tram-cdc-mysql-service
  ports:
    - "8099:8080"
  links:
    - mysql
    - kafka
    - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING: 1000
    EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING: 100
    EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS: 500
    SPRING_PROFILES_ACTIVE: EventuatePolling