zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.18.0.RELEASE
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

kafka:
  image: test-eventuateio-local-kafka
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181


mysql:
  image: eventuateio/eventuate-tram-mysql:0.7.0.RELEASE
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw
